## Random Dataset Generation + Array Filtering using NumPy

In [4]:
import numpy as np

### Generate random dataset

In [6]:
marks = np.random.randint(30, 101, 20)

print("Student Marks:")
print(marks)

Student Marks:
[75 46 62 85 79 77 69 68 71 81 34 32 71 88 98 83 32 80 81 66]


### Filter marks greater than 80

In [8]:
high_marks = marks[marks > 80]

print("Marks greater than 80:")
print(high_marks)

Marks greater than 80:
[85 81 88 98 83 81]


### Filter marks less than 40

In [10]:
failed_marks = marks[marks < 40]

print("Failed Marks:")
print(failed_marks)

Failed Marks:
[34 32 32]


### Filter marks between 50 and 70

In [11]:
average_marks = marks[(marks >= 50) & (marks <= 70)]

print("Marks between 50 and 70:")
print(average_marks)

Marks between 50 and 70:
[62 69 68 66]


### Count passed students

In [13]:
passed_students = np.sum(marks >= 40)

print("Number of passed students:", passed_students)

Number of passed students: 17


### Count failed students

In [16]:
failed_students = np.sum(marks < 40)

print("Number of failed students:", failed_students)

Number of failed students: 3


### Find highest, lowest, average marks

In [17]:
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))
print("Average Marks:", np.mean(marks))

Highest Marks: 98
Lowest Marks: 32
Average Marks: 68.9


## Full code

In [19]:
import numpy as np

marks = np.random.randint(30, 101, 20)

print("Student Marks:")
print(marks)

high_marks = marks[marks > 80]
print("\nMarks greater than 80:")
print(high_marks)

failed_marks = marks[marks < 40]
print("\nFailed Marks:")
print(failed_marks)

average_marks = marks[(marks >= 50) & (marks <= 70)]
print("\nMarks between 50 and 70:")
print(average_marks)

passed_students = np.sum(marks >= 40)
failed_students = np.sum(marks < 40)

print("\nNumber of passed students:", passed_students)
print("Number of failed students:", failed_students)

print("\nHighest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))
print("Average Marks:", np.mean(marks))

Student Marks:
[98 62 97 55 98 55 78 47 91 57 99 42 37 63 90 83 37 60 89 34]

Marks greater than 80:
[98 97 98 91 99 90 83 89]

Failed Marks:
[37 37 34]

Marks between 50 and 70:
[62 55 55 57 63 60]

Number of passed students: 17
Number of failed students: 3

Highest Marks: 99
Lowest Marks: 34
Average Marks: 68.6
