## Project: Sales Analyzer using NumPy

In [1]:
import numpy as np

### Create sales data

In [3]:
sales = np.array([
    [1200, 1500, 1000, 1800, 2000],
    [1300, 1600, 1100, 1700, 2100],
    [1250, 1550, 1050, 1900, 2200],
    [1400, 1650, 1150, 2000, 2300],
    [1500, 1700, 1200, 2100, 2400],
    [1600, 1800, 1300, 2200, 2500],
    [1700, 1900, 1400, 2300, 2600]
])

print("Sales Data:")
print(sales)

Sales Data:
[[1200 1500 1000 1800 2000]
 [1300 1600 1100 1700 2100]
 [1250 1550 1050 1900 2200]
 [1400 1650 1150 2000 2300]
 [1500 1700 1200 2100 2400]
 [1600 1800 1300 2200 2500]
 [1700 1900 1400 2300 2600]]


### Total sales of all products

In [4]:
total_sales = np.sum(sales)

print("Total Sales:", total_sales)

Total Sales: 59950


### Daily sales

In [5]:
daily_sales = np.sum(sales, axis=1)

print("Daily Sales:")
print(daily_sales)

Daily Sales:
[7500 7800 7950 8500 8900 9400 9900]


### Product-wise sales

In [6]:
product_sales = np.sum(sales, axis=0)

print("Product-wise Sales:")
print(product_sales)

Product-wise Sales:
[ 9950 11700  8200 14000 16100]


### Average sales

In [8]:
average_sales = np.mean(sales)

print("Average Sales:", average_sales)

Average Sales: 1712.857142857143


### Highest and lowest sales

In [9]:
highest_sale = np.max(sales)
lowest_sale = np.min(sales)

print("Highest Sale:", highest_sale)
print("Lowest Sale:", lowest_sale)

Highest Sale: 2600
Lowest Sale: 1000


### Best selling product

In [10]:
best_product_index = np.argmax(product_sales)

print("Best Selling Product: Product", best_product_index + 1)
print("Sales Amount:", product_sales[best_product_index])

Best Selling Product: Product 5
Sales Amount: 16100


### Worst selling product

In [11]:
worst_product_index = np.argmin(product_sales)

print("Worst Selling Product: Product", worst_product_index + 1)
print("Sales Amount:", product_sales[worst_product_index])

Worst Selling Product: Product 3
Sales Amount: 8200


### Filter sales greater than 2000

In [12]:
high_sales = sales[sales > 2000]

print("Sales greater than 2000:")
print(high_sales)

Sales greater than 2000:
[2100 2200 2300 2100 2400 2200 2500 2300 2600]


## Full Code

In [13]:
import numpy as np

sales = np.array([
    [1200, 1500, 1000, 1800, 2000],
    [1300, 1600, 1100, 1700, 2100],
    [1250, 1550, 1050, 1900, 2200],
    [1400, 1650, 1150, 2000, 2300],
    [1500, 1700, 1200, 2100, 2400],
    [1600, 1800, 1300, 2200, 2500],
    [1700, 1900, 1400, 2300, 2600]
])

print("Sales Data:")
print(sales)

total_sales = np.sum(sales)
print("\nTotal Sales:", total_sales)

daily_sales = np.sum(sales, axis=1)
print("\nDaily Sales:")
print(daily_sales)

product_sales = np.sum(sales, axis=0)
print("\nProduct-wise Sales:")
print(product_sales)

average_sales = np.mean(sales)
print("\nAverage Sales:", average_sales)

highest_sale = np.max(sales)
lowest_sale = np.min(sales)

print("\nHighest Sale:", highest_sale)
print("Lowest Sale:", lowest_sale)

best_product_index = np.argmax(product_sales)
worst_product_index = np.argmin(product_sales)

print("\nBest Selling Product: Product", best_product_index + 1)
print("Best Product Sales:", product_sales[best_product_index])

print("\nWorst Selling Product: Product", worst_product_index + 1)
print("Worst Product Sales:", product_sales[worst_product_index])

high_sales = sales[sales > 2000]
print("\nSales greater than 2000:")
print(high_sales)

Sales Data:
[[1200 1500 1000 1800 2000]
 [1300 1600 1100 1700 2100]
 [1250 1550 1050 1900 2200]
 [1400 1650 1150 2000 2300]
 [1500 1700 1200 2100 2400]
 [1600 1800 1300 2200 2500]
 [1700 1900 1400 2300 2600]]

Total Sales: 59950

Daily Sales:
[7500 7800 7950 8500 8900 9400 9900]

Product-wise Sales:
[ 9950 11700  8200 14000 16100]

Average Sales: 1712.857142857143

Highest Sale: 2600
Lowest Sale: 1000

Best Selling Product: Product 5
Best Product Sales: 16100

Worst Selling Product: Product 3
Worst Product Sales: 8200

Sales greater than 2000:
[2100 2200 2300 2100 2400 2200 2500 2300 2600]
