In [1]:
import numpy as np

### Create two matrices

In [2]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])

print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]


### Matrix Addition

In [3]:
addition = A + B

print("Matrix Addition:")
print(addition)

Matrix Addition:
[[ 6  8]
 [10 12]]


### Matrix Multiplication

###### Element-wise multiplication

In [4]:
element_multiply = A * B

print("Element-wise Multiplication:")
print(element_multiply)

Element-wise Multiplication:
[[ 5 12]
 [21 32]]


##### Real matrix multiplication

In [5]:
matrix_multiply = np.dot(A, B)

print("Matrix Multiplication:")
print(matrix_multiply)

Matrix Multiplication:
[[19 22]
 [43 50]]


##### or

In [7]:
matrix_multiply = A @ B
print(matrix_multiply)

[[19 22]
 [43 50]]


### Mean

In [9]:
mean_A = np.mean(A)

print("Mean of Matrix A:", mean_A)

Mean of Matrix A: 2.5


### Median

In [11]:
median_A = np.median(A)

print("Median of Matrix A:", median_A)

Median of Matrix A: 2.5


### Standard Deviation

In [12]:
std_A = np.std(A)

print("Standard Deviation of Matrix A:", std_A)

Standard Deviation of Matrix A: 1.118033988749895


## Full Code Together

In [13]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

addition = A + B
print("\nMatrix Addition:")
print(addition)

element_multiply = A * B
print("\nElement-wise Multiplication:")
print(element_multiply)

matrix_multiply = np.dot(A, B)
print("\nMatrix Multiplication:")
print(matrix_multiply)

mean_A = np.mean(A)
median_A = np.median(A)
std_A = np.std(A)

print("\nMean of Matrix A:", mean_A)
print("Median of Matrix A:", median_A)
print("Standard Deviation of Matrix A:", std_A)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix Addition:
[[ 6  8]
 [10 12]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]

Matrix Multiplication:
[[19 22]
 [43 50]]

Mean of Matrix A: 2.5
Median of Matrix A: 2.5
Standard Deviation of Matrix A: 1.118033988749895
